// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/account/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/account/delete.post').default>>>>
    }
    '/api/account': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/account/index.post').default>>>>
    }
    '/api/auth/forgot-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/forgot-password.post').default>>>>
    }
    '/api/auth/forgot-username': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/forgot-username.post').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/auth/signin': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/signin.post').default>>>>
    }
    '/api/auth/signout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/signout.post').default>>>>
    }
    '/api/external-id': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/external-id.post').default>>>>
    }
    '/api/image-upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image-upload.post').default>>>>
    }
    '/api/library/save': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/library/save.post').default>>>>
    }
    '/api/moderation/clear-session': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/moderation/clear-session.post').default>>>>
    }
    '/api/moderation/reset-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/moderation/reset-password.post').default>>>>
    }
    '/api/moderation/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/moderation/search.get').default>>>>
    }
    '/api/share/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/share/[id].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}